name: poetry

runs:
  steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
