name: Pipeline
on:
  pull_request:
    types:
    - opened
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/poetry
    
    - run: cd src/
    - run: poetry run python3 -m unittest discover ../tests
  
  black_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/poetry
    - run: poetry run black --check --diff src/
  
  isort_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/poetry
    - run: poetry run isort --profile --check-only -- diff src/
  
  flake8_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/poetry
    - run: poetry run flake8 src/
  
  mypy_analyzer:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/poetry
    - run: poetry run mypy src/
