name: Pipeline
on:
  pull_request:
    types:
    - opened
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
    
    - run: cd src/
    - run: poetry run python3 -m unittest discover ../tests
  
  black_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
    - run: poetry run black --check --diff src/
  
  isort_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
    - run: poetry run isort --profile black --check-only -- diff src/
  
  flake8_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
    - run: poetry run flake8 src/
  
  mypy_analyzer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
    - run: poetry run mypy src/
