name: Pipeline
on:
  pull_request:
    types:
    - opened
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
    
    - run: poetry run black
    - run: poetry run isort
    - run: poetry run flake8
    - run: poetry run mypy
