name: Pipeline
on:
  pull_request:
    types:
    - opened
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - name: Install dependencies
      run: poetry install && poetry shell
    - name: finishing
      run: echo The End
