name: Pipeline
on:
  pull_request:
    types:
    - opened
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry shell
    - run: poetry install
    
    - run: black --check --diff src/
    - run: isort --profile black --check-only --diff src/
    - run: flake8 src/
    - run: mypy src/
